server:
  port: ${PORT:8080}
  compression:
    enabled: true
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: ${JDBC_DATABASE_URL}
    driverClassName: org.postgresql.Driver
    hikari:
      connection-timeout: 30000

jwt:
  secret: ${SECRET_KEY}