server:
  compression:
    enabled: true
  ssl:
    enabled: true
    key-store: classpath:dark.p12
    key-store-password: ${PASSWORD}
    key-alias: dark
    key-store-type: PKCS12

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://${HOST}:5432/${DB_NAME}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver