server:
  compression:
    enabled: true

spring:
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: h2
    url: jdbc:h2:file:/Users/samyd/demo
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true